config/routes.rb
RailsEasyprost::Application.routes.draw do

  resources :extras

  resources :companions

  devise_for :users

  scope :admin do
    resources :users
  end

  root 'static_pages#home'

end

app/models/companion.rb
class Companion < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "180x180>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_and_belongs_to_many :extras
end

app/models/extra.rb
class Extra < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companions_controller.rb
class CompanionsController < ApplicationController
  before_action :set_companion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin, only: [:edit, :update, :destroy]

  # GET /companions
  # GET /companions.json
  def index
    @companions = Companion.all
  end

  # GET /companions/1
  # GET /companions/1.json
  def show
  end

  # GET /companions/new
  def new
    @companion = Companion.new
  end

  # GET /companions/1/edit
  def edit
  end

  # POST /companions
  # POST /companions.json
  def create
    @companion = Companion.new(companion_params)

    respond_to do |format|
      if @companion.save
        format.html { redirect_to @companion, notice: 'Companion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @companion }
      else
        format.html { render action: 'new' }
        format.json { render json: @companion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companions/1
  # PATCH/PUT /companions/1.json
  def update
    respond_to do |format|
      if @companion.update(companion_params)
        format.html { redirect_to @companion, notice: 'Companion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @companion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companions/1
  # DELETE /companions/1.json
  def destroy
    @companion.destroy
    respond_to do |format|
      format.html { redirect_to companions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_companion
      @companion = Companion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def companion_params
      params.require(:companion).permit(:name, :gender, :age, :price, :boobsize, :avatar, :extra_ids => [])
    end

  def is_admin
    redirect_to companions_path, notice: 'Você não tem permissão para isso.' unless current_user && current_user.admin?
  end
end

app/controllers/extras_controller.rb
class ExtrasController < ApplicationController
  before_action :set_extra, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin, only: [:edit, :update, :destroy]

  # GET /extras
  # GET /extras.json
  def index
    @extras = Extra.all
  end

  # GET /extras/1
  # GET /extras/1.json
  def show
  end

  # GET /extras/new
  def new
    @extra = Extra.new
  end

  # GET /extras/1/edit
  def edit
  end

  # POST /extras
  # POST /extras.json
  def create
    @extra = Extra.new(extra_params)

    respond_to do |format|
      if @extra.save
        format.html { redirect_to @extra, notice: 'Extra was successfully created.' }
        format.json { render action: 'show', status: :created, location: @extra }
      else
        format.html { render action: 'new' }
        format.json { render json: @extra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extras/1
  # PATCH/PUT /extras/1.json
  def update
    respond_to do |format|
      if @extra.update(extra_params)
        format.html { redirect_to @extra, notice: 'Extra was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @extra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extras/1
  # DELETE /extras/1.json
  def destroy
    @extra.destroy
    respond_to do |format|
      format.html { redirect_to extras_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extra
      @extra = Extra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extra_params
      params.require(:extra).permit(:name)
    end

  def is_admin
    redirect_to extras_path, notice: 'Você não tem permissão para isso.' unless current_user && current_user.admin?
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :is_admin

  def index
    @users = User.all
  end

  def edit
  end

  # PATCH/PUT /user/1
  # PATCH/PUT /user/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'Usuário atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:admin)
  end

  def is_admin
    redirect_to companions_path, notice: 'Você não tem permissão para acessar esta área.' unless current_user && current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companions_helper.rb
module CompanionsHelper
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companions/_form.html.erb
<%= form_for @companion, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
    <div class="control-group">
      <%= f.label :gender, :class => 'control-label' %>
      <div class="controls">
        <%= f.select(:gender, [['Masculino','Masculino'],['Feminino', "Feminino"]]) %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :age, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :age, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :price, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :price, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :boobsize, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :boobsize, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :avatar, :class => 'control-label' %>
      <div class="controls">
        <%= f.file_field :avatar %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :extras, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_check_boxes :extra_ids, Extra.all, :id, :name %>
      </div>
    </div>


    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  companions_path, :class => 'btn' %>
    </div>
<% end %>

app/views/companions/edit.html.erb
<%- model_class = Companion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companions/index.html.erb
<%- model_class = Companion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:boobsize) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companions.each do |companion| %>
      <tr>
        <td><%= link_to companion.id, companion_path(companion) %></td>
        <td><%= companion.gender %></td>
        <td><%= companion.age %></td>
        <td><%= companion.price %></td>
        <td><%= companion.boobsize %></td>
        <td><%= companion.name %></td>
        <td><%= image_tag companion.avatar.url(:thumb) %></td>
        <td><%= companion.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_companion_path(companion), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      companion_path(companion),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t('helpers.links.new')),
            new_companion_path,
            :class => 'btn btn-primary' %>

app/views/companions/new.html.erb
<%- model_class = Companion -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companions/show.html.erb
<%- model_class = Companion -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @companion.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @companion.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @companion.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:boobsize) %>:</strong></dt>
  <dd><%= @companion.boobsize %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @companion.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              companions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_companion_path(@companion), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              companion_path(@companion),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/extras/_form.html.erb
<%= form_for @extra, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                extras_path, :class => 'btn' %>
  </div>
<% end %>

app/views/extras/edit.html.erb
<%- model_class = Extra -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/extras/index.html.erb
<%- model_class = Extra -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @extras.each do |extra| %>
      <tr>
        <td><%= link_to extra.id, extra_path(extra) %></td>
        <td><%= extra.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_extra_path(extra), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      extra_path(extra),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_extra_path,
            :class => 'btn btn-primary' %>

app/views/extras/new.html.erb
<%- model_class = Extra -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/extras/show.html.erb
<%- model_class = Extra -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @extra.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              extras_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_extra_path(@extra), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              extra_path(@extra),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsEasyprost</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "EasyProst", root_path, class: "brand" %>
      <ul class="nav pull-right">
        <% if current_user && current_user.admin? %>
            <li><%= link_to "admin", users_path %></li>
        <% end %>
        <% if current_user %>
            <li><%= link_to "companions", companions_path %></li>
            <li><%= link_to "extras", extras_path %></li>
            <li><%= link_to "sign out", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <% if notice %>
    <p class="alert"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
   <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/static_pages/home.html.erb
<div class="hero-unit">
  <h1 class="center">EasyProst</h1><br>
  <p>Seja bem vindo ao EasyProst!</p>

  <%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-medium" %>
  <%= link_to "Cadastrar", new_user_registration_path, class: "btn btn-primary btn-medium" %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :admin, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :admin, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>